### ISSUE TITLE
월요일 밤 11시 레벨 테스트.

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/withcenter-office-management#54]
월요일 밤 11시 레벨 테스트.

그런데 학생이 아직 가입하지 않고, 전화로만 요청한 상태.

전화번호: 010-5437-9258 로, 밤 10시 30분 쯤 전화를 해서,
회원 가입 하시라고 하고,
회원 아이디로 레벨 테스트 예약 하고,
원격지원해서, 화상 수업 프로그램 설치하고,
11시에 강의실 입장 버튼을 누르라고 함.

**Comment by psw0222** [comment]
시간이 안된다고 하시면서 내일(18/7/17)로 연기 요청. 내일 재통화 예정
