### ISSUE TITLE
Take new photo and Video of teacher Nic

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/withcenter-office-management#73]
**Reason**
Photo and video are not appealing at all.

**Comment by HROEden** [comment]
I will work on it ASAP, Sir.

**Comment by HROEden** [comment]
Sir, the video introduction of Monique has been changed. The profile picture will follow. Thank you.

**Comment by HROEden** [comment]
Sir, we have already changed the profile picture of Nick. Kindly check it and tell me your thoughts. Thank you.
