### ISSUE TITLE
Student mike complain that teacher Jackie didn't call. on 2018-12-03. Ask teacher to send call history. and give it to Mr. Song before 5pm on 2018-12-06.

### ISSUE THREAD

**Issue by thruthesky** [thruthesky/withcenter-office-management#76]

**Comment by lancelynyrd** [comment]
![jackie](https://user-images.githubusercontent.com/17477197/49567359-6ae35b00-f968-11e8-8117-5ade758afe87.jpg)

![jackie2](https://user-images.githubusercontent.com/17477197/49567623-3de37800-f969-11e8-8876-cd61ed2e236b.jpg)

![jackie3](https://user-images.githubusercontent.com/17477197/49567629-4176ff00-f969-11e8-96f6-167943e11ea1.jpg)

![jackie4](https://user-images.githubusercontent.com/17477197/49567633-43d95900-f969-11e8-83bb-e7572b9c3b1e.jpg)
